version: '3'

services:

# servidor nginx
  web:
    image: nginx:latest
    volumes:
      - ./public_html:/usr/share/nginx/html
    ports:
      - 8080:80

# container de DB
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33060:3306
    volumes:
      - db:/var/lib/mysql
